version: '3.10' #version of docker-compose
services:
  db:
    image: postgres:14.1-alpine #pull postgres image from Dockerhub 
    restart: always
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      mynet:
        aliases:
          - db
  web:
    container_name: sampletodo
    build: .  
    depends_on:
      - db
    ports:
      - '127.0.0.1:8000:8080'
    environment:
      POSTGRES_URL: postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - './:/src'
    networks:
      mynet:

volumes: 
  db: 
    driver: local

networks:
  mynet:
    driver: bridge
